Metrics/LineLength:
  Exclude:
    - '*.gemspec'
    - 'spec/**/*_spec.rb'

Metrics/BlockLength:
  Exclude:
      - 'spec/**/*_spec.rb'

Style/SymbolProc:
  Exclude:
    - 'lib/utilise/augment/hash.rb'
