Metrics/LineLength:
  Exclude:
    - '*.gemspec'
    - 'spec/**/*_spec.rb'

Metrics/BlockLength:
  Exclude:
      - 'spec/**/*_spec.rb'

Lint/BooleanSymbol:
  Exclude:
    - 'spec/utilise/array_spec.rb'
    - 'spec/utilise/hash_spec.rb'
    - 'spec/utilise/object_spec.rb'
    - 'spec/utilise/symbol_spec.rb'
